// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bangthatzon.Migrations
{
    [DbContext(typeof(BangthatzonDbContext))]
    [Migration("20240830153859_ProductDataAdded")]
    partial class ProductDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bangthatzon.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Books"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Sports & Outdoors"
                        });
                });

            modelBuilder.Entity("Bangthatzon.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("OpenOrder")
                        .HasColumnType("boolean");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OpenOrder = false,
                            PaymentTypeId = 4,
                            PurchaseDate = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            OpenOrder = false,
                            PaymentTypeId = 1,
                            PurchaseDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            OpenOrder = true,
                            PaymentTypeId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            OpenOrder = true,
                            PaymentTypeId = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Bangthatzon.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNumber = "1234567812345678",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CardNumber = "2345678923456789",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CardNumber = "3456789034567890",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CardNumber = "4567890145678901",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Bangthatzon.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest model with all the features",
                            Image = "smartphone.jpg",
                            Price = 699.99m,
                            ProductName = "Smartphone",
                            QuantityAvailable = 50,
                            SellerId = 4
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brews coffee in minutes",
                            Image = "coffee_maker.jpg",
                            Price = 89.99m,
                            ProductName = "Coffee Maker",
                            QuantityAvailable = 20,
                            SellerId = 5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Noise-cancelling over-ear headphones",
                            Image = "headphones.jpg",
                            Price = 149.99m,
                            ProductName = "Headphones",
                            QuantityAvailable = 30,
                            SellerId = 6
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-quality mat for yoga and workouts",
                            Image = "yoga_mat.jpg",
                            Price = 39.99m,
                            ProductName = "Yoga Mat",
                            QuantityAvailable = 40,
                            SellerId = 7
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fast wireless charger for all devices",
                            Image = "wireless_charger.jpg",
                            Price = 29.99m,
                            ProductName = "Wireless Charger",
                            QuantityAvailable = 25,
                            SellerId = 8
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable tent for outdoor camping",
                            Image = "camping_tent.jpg",
                            Price = 119.99m,
                            ProductName = "Camping Tent",
                            QuantityAvailable = 15,
                            SellerId = 9
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stylish smartwatch with fitness tracking",
                            Image = "smartwatch.jpg",
                            Price = 249.99m,
                            ProductName = "Smartwatch",
                            QuantityAvailable = 22,
                            SellerId = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable and durable running shoes",
                            Image = "running_shoes.jpg",
                            Price = 79.99m,
                            ProductName = "Running Shoes",
                            QuantityAvailable = 60,
                            SellerId = 3
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-speed blender for smoothies",
                            Image = "blender.jpg",
                            Price = 99.99m,
                            ProductName = "Blender",
                            QuantityAvailable = 45,
                            SellerId = 5
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable e-book reader with backlight",
                            Image = "ebook_reader.jpg",
                            Price = 129.99m,
                            ProductName = "E-Book Reader",
                            QuantityAvailable = 33,
                            SellerId = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Official size and weight basketball",
                            Image = "basketball.jpg",
                            Price = 29.99m,
                            ProductName = "Basketball",
                            QuantityAvailable = 50,
                            SellerId = 7
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Next-gen gaming console with 4K support",
                            Image = "gaming_console.jpg",
                            Price = 499.99m,
                            ProductName = "Gaming Console",
                            QuantityAvailable = 10,
                            SellerId = 6
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stylish leather jacket for men",
                            Image = "leather_jacket.jpg",
                            Price = 199.99m,
                            ProductName = "Leather Jacket",
                            QuantityAvailable = 25,
                            SellerId = 8
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact digital camera with 20MP resolution",
                            Image = "digital_camera.jpg",
                            Price = 299.99m,
                            ProductName = "Digital Camera",
                            QuantityAvailable = 12,
                            SellerId = 9
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Non-stick cookware set for all your cooking needs",
                            Image = "cookware_set.jpg",
                            Price = 149.99m,
                            ProductName = "Cookware Set",
                            QuantityAvailable = 20,
                            SellerId = 5
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Foldable treadmill with multiple speed settings",
                            Image = "treadmill.jpg",
                            Price = 599.99m,
                            ProductName = "Treadmill",
                            QuantityAvailable = 8,
                            SellerId = 10
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable Bluetooth speaker with deep bass",
                            Image = "bluetooth_speaker.jpg",
                            Price = 89.99m,
                            ProductName = "Bluetooth Speaker",
                            QuantityAvailable = 70,
                            SellerId = 4
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "WiFi-enabled smart light bulbs with color change",
                            Image = "smart_light_bulbs.jpg",
                            Price = 49.99m,
                            ProductName = "Smart Light Bulbs",
                            QuantityAvailable = 100,
                            SellerId = 3
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fast boiling electric kettle with auto shut-off",
                            Image = "electric_kettle.jpg",
                            Price = 29.99m,
                            ProductName = "Electric Kettle",
                            QuantityAvailable = 30,
                            SellerId = 6
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Breathable running shorts for men",
                            Image = "running_shorts.jpg",
                            Price = 24.99m,
                            ProductName = "Running Shorts",
                            QuantityAvailable = 40,
                            SellerId = 8
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Best-selling fiction novel",
                            Image = "fiction_book.jpg",
                            Price = 14.99m,
                            ProductName = "Fiction Book",
                            QuantityAvailable = 60,
                            SellerId = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Replacement tent poles for camping",
                            Image = "tent_poles.jpg",
                            Price = 19.99m,
                            ProductName = "Tent Poles",
                            QuantityAvailable = 25,
                            SellerId = 9
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-performance laptop with SSD",
                            Image = "laptop.jpg",
                            Price = 999.99m,
                            ProductName = "Laptop",
                            QuantityAvailable = 15,
                            SellerId = 4
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Warm winter coat for extreme cold",
                            Image = "winter_coat.jpg",
                            Price = 149.99m,
                            ProductName = "Winter Coat",
                            QuantityAvailable = 35,
                            SellerId = 7
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact microwave oven with presets",
                            Image = "microwave_oven.jpg",
                            Price = 129.99m,
                            ProductName = "Microwave Oven",
                            QuantityAvailable = 22,
                            SellerId = 5
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supportive yoga block for all levels",
                            Image = "yoga_block.jpg",
                            Price = 12.99m,
                            ProductName = "Yoga Block",
                            QuantityAvailable = 50,
                            SellerId = 6
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "27-inch 4K monitor with adjustable stand",
                            Image = "monitor.jpg",
                            Price = 399.99m,
                            ProductName = "Monitor",
                            QuantityAvailable = 14,
                            SellerId = 10
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Slim fit jeans for men",
                            Image = "jeans.jpg",
                            Price = 49.99m,
                            ProductName = "Jeans",
                            QuantityAvailable = 40,
                            SellerId = 3
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Recipe book with 100+ easy meals",
                            Image = "cookbook.jpg",
                            Price = 19.99m,
                            ProductName = "Cookbook",
                            QuantityAvailable = 80,
                            SellerId = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight running hat with moisture-wicking",
                            Image = "running_hat.jpg",
                            Price = 19.99m,
                            ProductName = "Running Hat",
                            QuantityAvailable = 35,
                            SellerId = 4
                        });
                });

            modelBuilder.Entity("Bangthatzon.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Elm Street",
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            Image = "alice.jpg",
                            LastName = "Smith",
                            Uid = "user1",
                            Username = "alice.smith"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Avenue",
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            Image = "bob.jpg",
                            LastName = "Johnson",
                            Uid = "user2",
                            Username = "bob.johnson"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Road",
                            Email = "charlie.brown@example.com",
                            FirstName = "Charlie",
                            Image = "charlie.jpg",
                            LastName = "Brown",
                            Uid = "user3",
                            Username = "charlie.brown"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Maple Lane",
                            Email = "diana.williams@example.com",
                            FirstName = "Diana",
                            Image = "diana.jpg",
                            LastName = "Williams",
                            Uid = "user4",
                            Username = "diana.williams"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Birch Drive",
                            Email = "evan.jones@example.com",
                            FirstName = "Evan",
                            Image = "evan.jpg",
                            LastName = "Jones",
                            Uid = "user5",
                            Username = "evan.jones"
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Cedar Boulevard",
                            Email = "fiona.miller@example.com",
                            FirstName = "Fiona",
                            Image = "fiona.jpg",
                            LastName = "Miller",
                            Uid = "user6",
                            Username = "fiona.miller"
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 Elm Street",
                            Email = "george.davis@example.com",
                            FirstName = "George",
                            Image = "george.jpg",
                            LastName = "Davis",
                            Uid = "user7",
                            Username = "george.davis"
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 Oak Avenue",
                            Email = "hannah.wilson@example.com",
                            FirstName = "Hannah",
                            Image = "hannah.jpg",
                            LastName = "Wilson",
                            Uid = "user8",
                            Username = "hannah.wilson"
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Pine Road",
                            Email = "isaac.moore@example.com",
                            FirstName = "Isaac",
                            Image = "isaac.jpg",
                            LastName = "Moore",
                            Uid = "user9",
                            Username = "isaac.moore"
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Maple Lane",
                            Email = "jessica.taylor@example.com",
                            FirstName = "Jessica",
                            Image = "jessica.jpg",
                            LastName = "Taylor",
                            Uid = "user10",
                            Username = "jessica.taylor"
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("Bangthatzon.Models.Order", b =>
                {
                    b.HasOne("Bangthatzon.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId");

                    b.HasOne("Bangthatzon.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bangthatzon.Models.PaymentType", b =>
                {
                    b.HasOne("Bangthatzon.Models.User", "User")
                        .WithMany("PaymentTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bangthatzon.Models.Product", b =>
                {
                    b.HasOne("Bangthatzon.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangthatzon.Models.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("Bangthatzon.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangthatzon.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bangthatzon.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Bangthatzon.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PaymentTypes");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
